from typing import Optional, Protocol, Union

from aiogram.utils.chat_member import ChatMemberUnion


class BotService(Protocol):
    async def is_inline_enabled(self) -> bool: ...

    async def get_bot_states(self) -> dict[str, str]: ...

    async def get_my_name(self) -> str: ...

    async def get_referral_url(self, referral_code: str) -> str: ...

    async def get_plan_url(self, public_code: str) -> str: ...

    async def get_ad_link_url(self, code: str) -> str: ...

    def get_support_url(self, text: Optional[str] = None) -> str: ...

    async def get_chat_member(
        self,
        chat_id: Union[str, int],
        user_id: int,
    ) -> ChatMemberUnion: ...
