from typing import Any, Awaitable, Callable, Optional, Protocol, runtime_checkable


@runtime_checkable
class Cryptographer(Protocol):
    def encrypt(self, data: str) -> str: ...

    def encrypt_recursive(self, value: Any) -> Any: ...

    def decrypt(self, data: str) -> str: ...

    def decrypt_recursive(self, value: Any) -> Any: ...

    def get_hash(self, data: Any) -> str: ...

    def is_encrypted(self, value: str) -> bool: ...

    def generate_random_code(self, length: int = 6) -> str: ...

    async def generate_unique_code(
        self,
        is_taken: Callable[[str], Awaitable[Optional[Any]]],
        length: int = 6,
    ) -> str: ...
