from typing import Optional, Protocol, runtime_checkable

from src.application.dto import AdLinkDto, AdLinkStatsDto


@runtime_checkable
class AdLinkDao(Protocol):
    async def create(self, link: AdLinkDto) -> AdLinkDto: ...

    async def get_by_id(self, link_id: int) -> Optional[AdLinkDto]: ...

    async def get_by_code(self, code: str) -> Optional[AdLinkDto]: ...

    async def get_all(self) -> list[AdLinkDto]: ...

    async def update(self, link: AdLinkDto) -> Optional[AdLinkDto]: ...

    async def delete(self, link_id: int) -> bool: ...

    async def get_stats(self, link_id: int) -> AdLinkStatsDto: ...
