from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class AuthSessionDao(Protocol):
    async def store_refresh_token(self, token: str, user_id: int, ttl: int) -> None: ...

    async def get_user_id_by_refresh_token(self, token: str) -> Optional[int]: ...

    async def revoke_refresh_token(self, token: str) -> None: ...

    async def get_and_revoke_refresh_token(self, token: str) -> Optional[int]: ...

    async def revoke_all_user_tokens(self, user_id: int) -> None: ...
