from typing import Optional, Protocol, runtime_checkable

from src.application.dto import PlanDto
from src.core.enums import PlanAvailability


@runtime_checkable
class PlanDao(Protocol):
    async def create(self, plan: PlanDto) -> PlanDto: ...

    async def get_by_id(self, plan_id: int) -> Optional[PlanDto]: ...

    async def get_by_name(self, name: str) -> Optional[PlanDto]: ...

    async def get_active_plans(self) -> list[PlanDto]: ...

    async def get_active_trial_plans(self) -> list[PlanDto]: ...

    async def get_all(self) -> list[PlanDto]: ...

    async def get_by_public_code(self, public_code: str) -> Optional[PlanDto]: ...

    async def update(self, plan: PlanDto) -> Optional[PlanDto]: ...

    async def update_status(self, plan_id: int, is_active: bool) -> Optional[PlanDto]: ...

    async def delete(self, plan_id: int) -> bool: ...

    async def filter_by_availability(self, availability: PlanAvailability) -> list[PlanDto]: ...

    async def get_active_allowed_plans(self) -> list[PlanDto]: ...

    async def count_non_trial(self) -> int: ...

    async def set_order_index(self, plan_id: int, order_index: int) -> None: ...
