from typing import Optional, Protocol, runtime_checkable
from uuid import UUID

from src.application.dto import (
    PromocodeActivationDetailDto,
    PromocodeActivationDto,
    PromocodeDetailStatisticsDto,
    PromocodeDto,
    PromocodeStatisticsDto,
)


@runtime_checkable
class PromocodeDao(Protocol):
    async def create(self, promocode: PromocodeDto) -> PromocodeDto: ...

    async def update(self, promocode: PromocodeDto) -> Optional[PromocodeDto]: ...

    async def delete(self, promocode_id: int) -> bool: ...

    async def get_by_id(self, promocode_id: int) -> Optional[PromocodeDto]: ...

    async def get_by_code(self, code: str) -> Optional[PromocodeDto]: ...

    async def get_by_code_for_update(self, code: str) -> Optional[PromocodeDto]: ...

    async def get_list(self, limit: int = 100, offset: int = 0) -> list[PromocodeDto]: ...

    async def get_count(self) -> int: ...

    async def get_activations_count(self, promocode_id: int) -> int: ...

    async def get_statistics(self) -> PromocodeStatisticsDto: ...

    async def get_detail_statistics(
        self, promocode_id: int
    ) -> Optional[PromocodeDetailStatisticsDto]: ...

    async def get_activation_by_user(
        self, promocode_id: int, user_id: int
    ) -> Optional[PromocodeActivationDto]: ...

    async def get_activation_by_request_id(
        self, request_id: UUID, for_update: bool = False
    ) -> Optional[PromocodeActivationDto]: ...

    async def get_pending_activation_by_user(
        self, user_id: int
    ) -> Optional[PromocodeActivationDto]: ...

    async def get_pending_activations(self, limit: int = 100) -> list[PromocodeActivationDto]: ...

    async def lock_activation_user(self, user_id: int) -> None: ...

    async def lock_activation_request(self, request_id: UUID) -> None: ...

    async def get_activations_by_user(
        self, user_id: int, limit: int = 100, offset: int = 0
    ) -> list[PromocodeActivationDetailDto]: ...

    async def get_activations_count_by_user(self, user_id: int) -> int: ...

    async def create_activation(
        self,
        activation: PromocodeActivationDto,
        max_activations: Optional[int] = None,
        is_reusable: bool = False,
    ) -> PromocodeActivationDto: ...

    async def mark_activation_applied(self, request_id: UUID) -> PromocodeActivationDto: ...

    async def set_activation_error(self, request_id: UUID, error: str) -> None: ...
