from typing import Optional, Protocol, runtime_checkable
from uuid import UUID

from src.application.dto import PlanSubStatsDto, SubscriptionDto, SubscriptionStatsDto
from src.core.enums import SubscriptionStatus


@runtime_checkable
class SubscriptionDao(Protocol):
    async def create(self, subscription: SubscriptionDto, user_id: int) -> SubscriptionDto: ...

    async def get_by_id(self, subscription_id: int) -> Optional[SubscriptionDto]: ...

    async def get_by_remna_id(self, remna_id: UUID) -> Optional[SubscriptionDto]: ...

    async def get_all_by_user(self, user_id: int) -> list[SubscriptionDto]: ...

    async def get_current(self, user_id: int) -> Optional[SubscriptionDto]: ...

    async def update(self, subscription: SubscriptionDto) -> Optional[SubscriptionDto]: ...

    async def update_status(
        self,
        subscription_id: int,
        status: SubscriptionStatus,
    ) -> Optional[SubscriptionDto]: ...

    async def exists(self, remna_id: UUID) -> bool: ...

    async def count_active_by_plan(self, plan_id: int) -> int: ...

    async def get_all_active_internal_squads(self) -> list[UUID]: ...

    async def count_total_trials(self) -> int: ...

    async def count_converted_from_trial(self) -> int: ...

    async def get_stats(self) -> SubscriptionStatsDto: ...

    async def get_plan_sub_stats(self) -> list[PlanSubStatsDto]: ...
