from typing import Optional, Protocol, runtime_checkable
from uuid import UUID

from src.application.dto import UserDto
from src.core.enums import Role


@runtime_checkable
class UserDao(Protocol):
    async def create(self, user: UserDto) -> UserDto: ...

    async def get_by_id(self, user_id: int) -> Optional[UserDto]: ...

    async def get_by_telegram_id(self, telegram_id: int) -> Optional[UserDto]: ...

    async def get_by_remna_uuid(self, remna_uuid: UUID) -> Optional[UserDto]: ...

    async def get_by_email(self, email: str) -> Optional[UserDto]: ...

    async def get_by_telegram_ids(self, telegram_ids: list[int]) -> list[UserDto]: ...

    async def get_by_partial_name(self, query_name: str) -> list[UserDto]: ...

    async def get_by_referral_code(self, referral_code: str) -> Optional[UserDto]: ...

    async def get_all(self, limit: Optional[int] = None, offset: int = 0) -> list[UserDto]: ...

    async def update(self, user: UserDto) -> Optional[UserDto]: ...

    async def delete(self, user_id: int) -> bool: ...

    async def count(self) -> int: ...

    async def exists(self, user_id: int) -> bool: ...

    async def filter_by_role(self, role: list[Role]) -> list[UserDto]: ...

    async def set_trial_available(self, user_id: int, is_trial_available: bool) -> None: ...

    async def set_bot_blocked_status(self, user_id: int, is_bot_blocked: bool) -> None: ...

    async def set_current_subscription_by_id(self, user_id: int, subscription_id: int) -> None: ...

    async def clear_current_subscription(self, user_id: int) -> None: ...

    async def get_blocked_users(self) -> list[UserDto]: ...

    async def get_by_ids(self, user_ids: list[int]) -> list[UserDto]: ...

    async def get_recent_registered_users(self, limit: int = 5) -> list[UserDto]: ...

    async def unblock_all(self) -> None: ...

    async def count_blocked(self) -> int: ...

    async def has_any_subscription(
        self,
        user_id: int,
        *,
        include_trial: bool = True,
    ) -> bool: ...

    async def is_invited_user(self, user_id: int) -> bool: ...

    async def toggle_blocked_status(self, user_id: int) -> None: ...

    async def count_active_non_blocked(self) -> int: ...

    async def count_with_active_subscription(self) -> int: ...

    async def count_without_subscription(self) -> int: ...

    async def count_with_expired_subscription(self) -> int: ...

    async def count_with_trial_subscription(self) -> int: ...

    async def get_active_non_blocked(self) -> list[UserDto]: ...

    async def get_active_by_plan(self, plan_id: int) -> list[UserDto]: ...

    async def get_with_active_subscription(self) -> list[UserDto]: ...

    async def get_without_subscription(self) -> list[UserDto]: ...

    async def get_with_expired_subscription(self) -> list[UserDto]: ...

    async def get_with_trial_subscription(self) -> list[UserDto]: ...

    async def count_new(self, days: int) -> int: ...

    async def count_bot_blocked(self) -> int: ...

    async def block_by_telegram_ids(self, telegram_ids: list[int]) -> int: ...
